[theme]
primaryColor = "#4B0082"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#111"

[server]
headless = true

[client]
showSidebarNavigation = true

[general]
pageTitle = "Ryxon Risk Dashboard"
